CREATE TABLE IF NOT EXISTS users (
  _id           SERIAL PRIMARY KEY, 
  username      VARCHAR(255) UNIQUE NOT NULL,
  password      VARCHAR(255) NOT NULL,
  created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);